<a href="https://colab.research.google.com/github/patansulthana-student/pandas-practice/blob/main/Pandas_Series_and_DataFrame_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import pandas as pd

data = {
    "Name": ["Asha", "Ravi", "Sita", "Rahul", "Priya", "John"],
    "Age": [20, 21, 19, 22, 20, 23],
    "Marks": [85, 90, 78, 88, 95, 82]
}

df = pd.DataFrame(data)

print("1. HEAD - First 5 rows")
display(df.head())

print("2. TAIL - Last 5 rows")
display(df.tail())

print("3. SHAPE - Number of rows and columns")
print(df.shape)

print("4. DESCRIBE - Statistical summary")
display(df.describe())

1. HEAD - First 5 rows

    Name  Age  Marks
0   Asha   20     85
1   Ravi   21     90
2   Sita   19     78
3  Rahul   22     88
4  Priya   20     95

2. TAIL - Last 5 rows

    Name  Age  Marks
1   Ravi   21     90
2   Sita   19     78
3  Rahul   22     88
4  Priya   20     95
5   John   23     82

3. SHAPE - Number of rows and columns
(6, 3)
4. DESCRIBE - Statistical summary

             Age      Marks
count   6.000000   6.000000
mean   20.833333  86.333333
std     1.471960   6.022181
min    19.000000  78.000000
25%    20.000000  82.750000
50%    20.500000  86.500000
75%    21.750000  89.500000
max    23.000000  95.000000

In [ ]:
#series object is one dimensional label array
import pandas as pd
s1=pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
#Changing Index
import pandas as pd
s1=pd.Series([1,2,3,4,5])
s1

import pandas as pd
s1=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
s1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
#Series object from dictionary
import pandas as pd
pd.Series({'a':10,'b':20,'c':30})

a    10
b    20
c    30
dtype: int64

In [ ]:
#changing index position
import pandas as pd
pd.Series({'a':10,'b':20,'c':30},index=['b','c','d','a'])

b    20.0
c    30.0
d     NaN
a    10.0
dtype: float64

In [ ]:
#Extracting Individual Elements
#Extracting Single Element
import pandas as pd
s1 = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(s1[3])

4

In [ ]:
#Extracting a Sequence of elements
s1=pd.Series([1,2,3,4,5,6,7,8,9])
s1[:4]

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
#Extracting elemnts from back
s1=pd.Series([1,2,3,4,5,6,7,8,9])
s1[-3:]

6    7
7    8
8    9
dtype: int64